name: localwork
on:
    push:
        branches: ['main']
    workflow_dispatch:

    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout our code to the ubuntu latest
          uses: actions/checkout@v4
        - name: login to docker hub, build our image and push
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{secrets.DOCKER_TOKEN}}
        - name: build images from docker file
          run: docker build -t ${{ vars.DOCKER_USERNAME }}/santana .
        - name: push images to docker hub
          run: docker push ${{ vars.DOCKER_USERNAME }}/santana

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Execute remote SSH commands using secret key
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.AWS_SERVER_HOST}}
            username: ${{secrets.AWS_USERNAME}}
            key: ${{ secrets.AWS_SECURITY_KEY }}
            script: |
                sudo docker pull ${{ vars.DOCKER_USERNAME }}/santana
                sudo docker run --name=santana -p 8000:80 -d ${{ vars.DOCKER_USERNAME }}/santana




    
